name: "Notify Deployment"
description: "Sends a deployment notification to configured webhooks."

inputs:
  gitdailies-url:
    description: "Webhook endpoint URL (pass org variable GITDAILIES_WEBHOOK_URL)"
    required: true
  gitdailies-key:
    description: "Webhook authentication key (pass org secret GITDAILIES_WEBHOOK_KEY)"
    required: true
  grafana-url:
    description: "Grafana Cloud API endpoint URL (pass org variable GRAFANA_CLOUD_URL)"
    required: true
  grafana-key:
    description: "Grafana Cloud API token (pass org secret GRAFANA_CLOUD_API_TOKEN)"
    required: true
  repo:
    description: "Repository (owner/repo)"
    required: false
    default: ${{ github.repository }}
  branch:
    description: "Branch name"
    required: false
    default: ${{ github.ref_name }}
  commit-sha:
    description: "Commit SHA"
    required: false
    default: ${{ github.sha }}
  environment:
    description: "Deployment environment (prd, tst, dev, sbx)"
    required: false
    default: "prd"
  image:
    description: "Deployed image name and tag"
    required: false
    default: ""
  deployment-start-time:
    description: "Deployment start time, Epoch in milliseconds"
    required: false
    default: ""
  deployment-end-time:
    description: "Deployment end time, Epoch in milliseconds"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Notify GitDailies
      continue-on-error: true
      shell: bash
      env:
        GITDAILIES_URL: ${{ inputs.gitdailies-url }}
        GITDAILIES_KEY: ${{ inputs.gitdailies-key }}
        REPO: ${{ inputs.repo }}
        BRANCH: ${{ inputs.branch }}
        COMMIT_SHA: ${{ inputs.commit-sha }}
      run: ${github.action_path}/bash/notify_gitdailies.sh

    - name: Notify Grafana Cloud of deployment
      continue-on-error: true
      shell: bash
      env:
        GRAFANA_URL: ${{ inputs.grafana-url }}
        GRAFANA_API_TOKEN: ${{ inputs.grafana-key }}
        REPO: ${{ inputs.repo }}
        BRANCH: ${{ inputs.branch }}
        COMMIT_SHA: ${{ inputs.commit-sha }}
        START_TIME: ${{ inputs.deployment-start-time }}
        END_TIME: ${{ inputs.deployment-end-time }}
        ENVIRONMENT: ${{ inputs.environment }}
        IMAGE: ${{ inputs.image }}
      run: ${github.action_path}/bash/notify_grafana.sh

    - name: Check for curl errors
      if: always()
      continue-on-error: true
      shell: bash
      run: ${github.action_path}/bash/send_errors_to_sentry.sh
