name: CI
run-name: Verifying commit ${{ github.sha }} on branch ${{ github.ref_name }}

on:
  push:
    branches:
      - main
  pull_request:
  pull_request_review:
    types: [submitted]

jobs:
  versions:
    uses: ./.github/workflows/tools-versions.yml

  test:
    needs: versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ needs.versions.outputs.python }}
      - name: Set up Poetry
        uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 # v1.4.2
        with:
          version: ${{ needs.versions.outputs.poetry }}
      - name: Install dependencies
        run: poetry install --no-interaction --no-root --with dev
      - name: Test bash scripts (with Python)
        run: poetry run poe test

  update-notify-deployment-doc:
    needs:
      - versions
    uses: ./.github/workflows/auto-doc.yml
    with:
      action_file: .github/actions/notify-deployment/action.yml
      readme_file: README-notify-deployment.md

  ci:
    name: CI
    needs: [versions, test, update-notify-deployment-doc]
    if: ${{ !cancelled() }}
    runs-on: ubuntu-24.04
    steps:
      - name: All required CI jobs passed
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
            echo "::error::A required CI job failed"
            exit 1
          fi
