name: ci
run-name: Verifying commit ${{ github.sha }} on branch ${{ github.ref_name }}

on:
  push:
    branches:
      - main
  pull_request:
  pull_request_review:
    types: [submitted]

jobs:
  verify-pr:
    name: Verify PR
    if: ${{ github.event_name == 'pull_request' }}
    uses: entur/gha-meta/.github/workflows/verify-pr.yml@v1

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
        with:
          version: "2.1.3"
      - name: Test bash scripts (with Python)
        run: poetry run poe test

  update-notify-deployment-doc:
    needs:
      - verify-pr
    uses: ./.github/workflows/auto-doc.yml
    with:
      action_file: .github/actions/notify-deployment/action.yml
      readme_file: README-notify-deployment.md
